2.2
javascript-tutorial/cs.javascript.info pull request #67
Opened 2022-04-10 18:22 UTC by otmon76

2022-04-16 14:02 UTC, danipoma requested changes

2022-04-29 20:00 UTC, danipoma requested changes

2022-04-30 17:56 UTC, otmon76 commented on 1-js/02-first-steps/02-structure/article.md
> +Doporučujeme vám psát středníky mezi příkazy i tehdy, když je odděluje konec řádku. Toto pravidlo je v komunitě všeobecně přijímáno. Zmíníme to ještě jednou -- ve většině případů *je možné* středník
správně je "ve většině případů" (ve většině koho, čeho - přívlastek neshodný)

2022-04-30 18:21 UTC, otmon76 commented
/done

2022-04-30 18:23 UTC, danipoma commented on 1-js/02-first-steps/02-structure/article.md
> +Doporučujeme vám psát středníky mezi příkazy i tehdy, když je odděluje konec řádku. Toto pravidlo je v komunitě všeobecně přijímáno. Zmíníme to ještě jednou -- ve většině případů *je možné* středník
Pravda, souhlasím s vámi. Nevím, co me to tehdy napadlo.

2022-04-30 18:27 UTC, danipoma commented
/done

2022-04-30 18:28 UTC, danipoma approved these changes

2022-04-30 18:28 UTC, merged