2.3
javascript-tutorial/cs.javascript.info pull request #68
Opened 2022-04-10 18:23 UTC by otmon76

2022-04-17 20:49 UTC, danipoma requested changes

2022-04-17 20:49 UTC, danipoma commented on 1-js/02-first-steps/03-strict-mode/article.md
> +Za prvé, můžete zkusit vložit více řádků pomocí `key:Shift+Enter` a umístit `use strict` na začátek, například takto:
```suggestion
Můžete zkusit vložit více řádků pomocí zkratky `key:Shift+Enter` a umístit `use strict` na začátek, například takto:
```

2022-04-17 20:49 UTC, danipoma commented on 1-js/02-first-steps/03-strict-mode/article.md
> +Někdy, když `use strict` znamená rozdíl, dostanete nesprávné výsledky.
```suggestion
Někdy to může ovlivnit i samotný výsledek.
```

2022-04-17 20:49 UTC, danipoma commented on 1-js/02-first-steps/03-strict-mode/article.md
> +Pokud to nefunguje, např. v nějakém starém prohlížeči, existuje jeden nepěkný, ale spolehlivý způsob, jak zajistit `use strict`. Umístěte jej do tohoto wrapperu:
```suggestion
Pokud to nefunguje, např. v nějakém starém prohlížeči, existuje jeden nepěkný, ale spolehlivý způsob, jak zajistit `use strict`. Umístěte jej do tohoto obalu:
```

2022-04-17 20:49 UTC, danipoma commented on 1-js/02-first-steps/03-strict-mode/article.md
> +Můžeme doporučit, abyste zahajovali skripty `"use strict"`... ale víte, co je fajn?
```suggestion
Můžeme vám doporučit, abyste zahajovali skripty s `"use strict"`... ale víte, co je fajn?
```

2022-04-17 20:49 UTC, danipoma commented on 1-js/02-first-steps/03-strict-mode/article.md
> +Až se v dalších kapitolách naučíme další vlastnosti jazyka, poznáme rozdíly mezi striktním a starším režimem. Naštěstí jich není mnoho a ve skutečnosti nám spíše zlepšují život.
```suggestion
Až se v dalších kapitolách naučíme další vlastnosti jazyka, poznáme rozdíly mezi striktním a starším režimem. Naštěstí jich není mnoho a ve skutečnosti nám spíše ulehčují práci.
```

2022-04-29 20:04 UTC, danipoma requested changes

2022-04-29 20:04 UTC, danipoma commented on 1-js/02-first-steps/03-strict-mode/article.md
>  ...
```suggestion
…
```

2022-04-29 20:04 UTC, danipoma commented on 1-js/02-first-steps/03-strict-mode/article.md
> +//  ...váš kód
```suggestion
//  …váš kód
```

2022-04-29 20:04 UTC, danipoma commented on 1-js/02-first-steps/03-strict-mode/article.md
> +  // ...zde je váš kód...
```suggestion
  // …zde je váš kód…
```

2022-04-29 20:04 UTC, danipoma commented on 1-js/02-first-steps/03-strict-mode/article.md
> +// níže uvedený "use strict" se ignoruje - musí být na začátku
```suggestion
// níže uvedený "use strict" se ignoruje – musí být na začátku
```

2022-04-29 20:04 UTC, danipoma commented on 1-js/02-first-steps/03-strict-mode/article.md
> +Moderní JavaScript podporuje „třídy“ a „moduly“ - pokročilé jazykové struktury (určitě se k nim dostaneme), které používají `use strict` automaticky. Pokud je tedy používáme, nemusíme direktivu `use
```suggestion
Moderní JavaScript podporuje „třídy“ a „moduly“ – pokročilé jazykové struktury (určitě se k nim dostaneme), které používají `use strict` automaticky. Pokud je tedy používáme, nemusíme direktivu `use strict` přidávat.
```

2022-05-01 17:53 UTC, merged

2022-05-01 17:53 UTC, otmon76 commented
/done

2022-05-01 20:05 UTC, otmon76 commented
nechtěně jsem udělal merge, pak jsem to revertnul, bohužel PR už asi nejde znovu otevřít, merge potom uděláme ručně