1.2.5
javascript-tutorial/cs.javascript.info pull request #70
Opened 2022-04-18 20:27 UTC by otmon76

2022-04-29 16:21 UTC, danipoma requested changes

2022-04-29 16:21 UTC, danipoma commented on 1-js/02-first-steps/05-types/article.md
> +Booleovské hodnoty podrobně probereme v kapitole <info:logical-operators>.
```suggestion
Datový typ boolean probereme podrobněji v kapitole <info:logical-operators>.
```

2022-04-29 16:21 UTC, danipoma commented on 1-js/02-first-steps/05-types/article.md
> +Speciální hodnota `null` nepatří k žádnému z výše uvedených typů. Tvoří samostatný typ, který obsahuje jedině hodnotu `null`:
```suggestion
Speciální hodnota `null` nepatří k žádnému z výše uvedených typů.
```

2022-04-29 16:21 UTC, danipoma commented on 1-js/02-first-steps/05-types/article.md
> -It forms a separate type of its own which contains only the `null` value:
Tvoří samostatný typ, který obsahuje jedině hodnotu `null`:

2022-04-29 16:21 UTC, danipoma commented on 1-js/02-first-steps/05-types/article.md
> +V JavaScriptu `null` není „odkaz na neexistující objekt“ nebo „nulový ukazatel“, jako v některých jiných jazycích. Je to speciální hodnota, která představuje „nic“, „prázdno“ nebo „neznámá hodnota“.
```suggestion
V JavaScriptu `null` není „odkaz na neexistující objekt“ nebo „nulový ukazatel“, jako v některých jiných jazycích.
```

2022-04-29 16:21 UTC, danipoma commented on 1-js/02-first-steps/05-types/article.md
> -It's just a special value which represents "nothing", "empty" or "value unknown".
Je to speciální hodnota, která představuje „nic“, „prázdno“ nebo „neznámá hodnota“.

2022-04-29 16:21 UTC, danipoma commented on 1-js/02-first-steps/05-types/article.md
> +...Toto však nedoporučujeme. Běžně se k přiřazení „prázdné“ nebo „neznámé“ hodnoty do proměnné používá `null`, zatímco `undefined` je vyhrazeno jako defaultní úvodní hodnota nepřiřazených proměnných.
Správně bychom měli vyjadřovat tři tečky nikoliv třema tečkama, ale znakem, který k tomu slouží – elipsou (…). Stejně jako bychom místo spojovníků měli používat pomlčky (–) tam kde mají být, ne spojovník (-).
```suggestion
…Toto však nedoporučujeme. Běžně se k přiřazení „prázdné“ nebo „neznámé“ hodnoty do proměnné používá `null`, zatímco `undefined` je vyhrazeno jako výchozí úvodní hodnota u proměnných, kterým nebyla hodnota přiřazena.
```

2022-04-29 16:21 UTC, danipoma commented on 1-js/02-first-steps/05-types/article.md
> +Když jsou objekty tak důležité, vyžadují zvláštní zacházení. Budeme o nich hovořit později v kapitole <info:object>, až se dozvíme víc o primitivních typech.
```suggestion
Když jsou objekty tak důležité, vyžadují zvláštní zacházení. Budeme o nich hovořit později v kapitole <info:object>, až se dozvíme více o primitivních typech.
```

2022-04-29 16:21 UTC, danipoma commented on 1-js/02-first-steps/05-types/article.md
> +Typ `symbol` se používá k vytváření unikátních identifikátorů pro objekty. Musíme jej zde zmínit, aby seznam byl úplný, ale podrobnosti necháme až na dobu, kdy budeme znát objekty.
```suggestion
Typ `symbol` se používá k vytváření unikátních identifikátorů pro objekty. Musíme jej zde zmínit, aby seznam byl úplný, ale podrobnosti si necháme až na dobu, kdy budeme vědět více o objektech.
```

2022-04-29 16:21 UTC, danipoma commented on 1-js/02-first-steps/05-types/article.md
> +- `string` pro řetězce. Řetězec může mít nula nebo více znaků. Neexistuje zvláštní typ pro jediný znak.
```suggestion
- `string` pro řetězce. Řetězec může mít nula nebo více znaků. Neexistuje datový typ pro znak.
```

2022-04-29 20:10 UTC, danipoma requested changes

2022-04-29 20:10 UTC, danipoma commented on 1-js/02-first-steps/05-types/1-string-quotes/solution.md
> +Obrácené čárky vkládají do řetězce hodnotu výrazu uvnitř `${...}`.
```suggestion
Obrácené čárky vkládají do řetězce hodnotu výrazu uvnitř `${…}`.
```

2022-04-29 20:10 UTC, danipoma commented on 1-js/02-first-steps/05-types/article.md
> +- `NaN` (z anglického „not a number“ -- není číslo) představuje výpočetní chybu. Je to výsledek nekorektní nebo nedefinované matematické operace, například:
```suggestion
- `NaN` (z anglického „not a number“ – není číslo) představuje výpočetní chybu. Je to výsledek nekorektní nebo nedefinované matematické operace, například:
```

2022-04-29 20:10 UTC, danipoma commented on 1-js/02-first-steps/05-types/article.md
> +- `null` pro neznámé hodnoty -- samostatný typ, který má jedinou hodnotu `null`.
```suggestion
- `null` pro neznámé hodnoty – samostatný typ, který má jedinou hodnotu `null`.
```

2022-04-29 20:10 UTC, danipoma commented on 1-js/02-first-steps/05-types/article.md
> +- `undefined` pro nepřiřazené hodnoty -- samostatný typ, který má jedinou hodnotu `undefined`.
```suggestion
- `undefined` pro nepřiřazené hodnoty – samostatný typ, který má jedinou hodnotu `undefined`.
```

2022-04-29 20:10 UTC, danipoma commented on 1-js/02-first-steps/05-types/article.md
> +- Pro `null` vrátí `"object"` -- to je chyba jazyka, ve skutečnosti to není objekt.
```suggestion
- Pro `null` vrátí `"object"` – to je chyba jazyka, ve skutečnosti to není objekt.
```

2022-05-01 18:19 UTC, merged

2022-05-01 18:19 UTC, otmon76 commented
/done

2022-05-01 20:05 UTC, otmon76 commented
nechtěně jsem udělal merge, pak jsem to revertnul, bohužel PR už asi nejde znovu otevřít, merge potom uděláme ručně