1.2.7
javascript-tutorial/cs.javascript.info pull request #73
Opened 2022-04-18 20:30 UTC by otmon76

2022-04-21 21:51 UTC, danipoma requested changes

2022-04-21 21:51 UTC, danipoma commented on 1-js/02-first-steps/07-type-conversions/article.md
> +Konverze na řetězec se odehraje tehdy, když potřebujeme hodnotu ve formě řetězce. Provádí ji například `alert(hodnota)`, aby mohla zobrazit hodnotu.
Zbytek řádku má být dle angl. předlohy na řádku 19.

```suggestion
Konverze na řetězec se odehraje tehdy, když potřebujeme hodnotu ve formě řetězce.
```

2022-04-21 21:51 UTC, danipoma commented on 1-js/02-first-steps/07-type-conversions/article.md
> -For example, `alert(value)` does it to show the value.
Provádí ji například `alert(hodnota)`, aby mohla zobrazit hodnotu.

2022-04-21 21:51 UTC, danipoma commented on 1-js/02-first-steps/07-type-conversions/article.md
> +alert( Number("123z") );      // NaN (chyba při čtení čísla v písmenu "z")
```suggestion
alert( Number("123z") );      // NaN (chyba při čtení čísla u znaku "z")
```

2022-04-21 21:51 UTC, danipoma commented on 1-js/02-first-steps/07-type-conversions/article.md
> +Konverze na boolean je nejjednodušší. Odehrává se v logických operátorech (později se setkáme s testy platnosti podmínky a podobnými věcmi), ale můžeme ji provést i explicitně voláním `Boolean(value)
Má být o 2 řádky níže.
```suggestion
Konverze na boolean je nejjednodušší.
```

2022-04-21 21:51 UTC, danipoma commented on 1-js/02-first-steps/07-type-conversions/article.md
> -It happens in logical operations (later we'll meet condition tests and other similar things) but can also be performed explicitly with a call to `Boolean(value)`.
Odehrává se v logických operátorech (později se setkáme s testy platnosti podmínky a podobnými věcmi), ale můžeme ji provést i explicitně voláním `Boolean(hodnota)`.

2022-04-21 21:51 UTC, danipoma commented on 1-js/02-first-steps/07-type-conversions/article.md
>  alert(typeof num); // number
```suggestion
alert(typeof num); // number (číslo)
```

2022-04-21 21:51 UTC, danipoma commented on 1-js/02-first-steps/07-type-conversions/article.md
>  alert(typeof str); // string
```suggestion
alert(typeof str); // string (řetězec)
```

2022-04-21 21:51 UTC, danipoma commented on 1-js/02-first-steps/07-type-conversions/article.md
> +alert(typeof hodnota); // string
```suggestion
alert(typeof hodnota); // string (řetězec)
```

2022-04-21 21:51 UTC, danipoma commented on 1-js/02-first-steps/07-type-conversions/article.md
> +**`Konverze na řetězec`** -- Nastává, když něco vypisujeme. Můžeme ji provést pomocí `String(value)`. Konverze na řetězec je u primitivních hodnot obvykle zřejmá.
```suggestion
**`Konverze na řetězec`** -- Nastává, když něco vypisujeme. Můžeme ji provést pomocí `String(hodnota)`. Konverze na řetězec je u primitivních typů obvykle zřejmá.
```

2022-04-21 21:51 UTC, danipoma commented on 1-js/02-first-steps/07-type-conversions/article.md
> +**`Konverze na číslo`** -- Nastává při matematických operacích. Můžeme ji provést pomocí `Number(value)`.
```suggestion
**`Konverze na číslo`** -- Nastává při matematických operacích. Můžeme ji provést pomocí `Number(hodnota)`.
```

2022-04-21 21:51 UTC, danipoma commented on 1-js/02-first-steps/07-type-conversions/article.md
> +**`Konverze na boolean`** -- Nastává při logických operacích. Můžeme ji provést pomocí `Boolean(value)`.
```suggestion
**`Konverze na boolean`** -- Nastává při logických operacích. Můžeme ji provést pomocí `Boolean(hodnota)`.
```

2022-04-21 21:51 UTC, danipoma commented on 1-js/02-first-steps/07-type-conversions/article.md
> +- `"0"` a řetězce obsahující jen mezery, např. `"   "`, převedené na boolean jsou true.
```suggestion
- `"0"` a řetězce obsahující jen mezery, např. `"   "`, jsou po převodu na boolean vyhodnoceny jako true.
```

2022-04-21 21:51 UTC, danipoma commented on 1-js/02-first-steps/07-type-conversions/article.md
> +O objektech se zde nezmiňujeme. Později, až se v JavaScriptu naučíme další základní věci, se k nim vrátíme v kapitole <info:object-toprimitive>, která je věnována výlučně objektům.
```suggestion
O objektech se zde nezmiňujeme. Později, až se v JavaScriptu naučíme všechny potřebné základy, se k nim vrátíme v kapitole <info:object-toprimitive>, která je věnována výlučně objektům.
```

2022-04-29 20:36 UTC, danipoma requested changes

2022-04-29 20:36 UTC, danipoma commented on 1-js/02-first-steps/07-type-conversions/article.md
> +| Hodnota |  Převede se na... |
```suggestion
| Hodnota |  Převede se na… |
```

2022-04-29 20:36 UTC, danipoma commented on 1-js/02-first-steps/07-type-conversions/article.md
> +| Hodnota |  Převede se na... |
```suggestion
| Hodnota |  Převede se na… |
```

2022-04-29 20:36 UTC, danipoma commented on 1-js/02-first-steps/07-type-conversions/article.md
> +| Hodnota |  Převede se na... |
```suggestion
| Hodnota |  Převede se na… |
```

2022-05-01 18:28 UTC, merged

2022-05-01 18:30 UTC, otmon76 commented
/done

2022-05-01 20:06 UTC, otmon76 commented
nechtěně jsem udělal merge, pak jsem to revertnul, bohužel PR už asi nejde znovu otevřít, merge potom uděláme ručně