1.2.16
javascript-tutorial/cs.javascript.info pull request #82
Opened 2022-04-18 20:40 UTC by otmon76

2022-07-24 11:12 UTC, danipoma commented on 1-js/02-first-steps/16-function-expressions/article.md
> +Zde je funkce vytvořena a výslovně přiřazena do proměnné jako kterákoli jiná hodnota. Nezáleží na tom, jak je funkce definována. Je to jen hodnota uložená do proměnné `řekniAhoj`.
```suggestion
Zde vidíme proměnnou `řekniAhoj`, do níž je uložena hodnota, kterou je nová funkce, vytvořená jako `function() { alert("Ahoj"); }`.
```

2022-07-24 11:12 UTC, danipoma commented on 1-js/02-first-steps/16-function-expressions/article.md
> +Význam obou částí kódu je stejný: „vytvořit funkci a uložit ji do proměnné `řekniAhoj`“.
```suggestion
Protože k vytvoření funkce dochází v kontextu přiřazovacího výrazu (na pravé straně `=`), je to *funkční výraz*.
```

2022-07-24 11:20 UTC, danipoma commented on 1-js/02-first-steps/16-function-expressions/article.md
> +řekniAhoj(); // Ahoj     //     tohle pořád funguje taky (proč by nemělo)
```suggestion
řekniAhoj(); // Ahoj     //     i tohle stále funguje (proč by nemělo)
```

2022-07-24 11:25 UTC, danipoma commented on 1-js/02-first-steps/16-function-expressions/article.md
> +## Callbackové funkce
```suggestion
## Funkce zpětného volaní (callback funkce)
```

2022-07-24 11:37 UTC, danipoma commented on 1-js/02-first-steps/16-function-expressions/article.md
> +Je to způsobeno vnitřními algoritmy. Když JavaScript připravuje spuštění skriptu, nejprve v něm najde globální deklarace funkcí a tyto funkce vytvoří. Můžeme to považovat za „inicializační krok“.
```suggestion
Je to způsobeno vnitřními algoritmy. Když JavaScript připravuje spuštění skriptu, nejprve v něm najde globální deklarace funkcí a tyto funkce vytvoří. Můžeme to považovat za „přípravnou fázi“.
```

2022-07-24 11:42 UTC, danipoma commented on 1-js/02-first-steps/16-function-expressions/article.md
> +    alert("Zdravíme vás!");
```suggestion
    alert("Dobrý den!");
```

2022-07-24 11:50 UTC, danipoma requested changes
Removed two paragraphs since they were not in source files anymore and also changed some text without suggestion since it was clear translation inconsistency. 

Please take a look on my suggestions.

2022-07-25 20:43 UTC, otmon76 commented
"Removed two paragraphs since they were not in source files anymore and also changed some text without suggestion since it was clear translation inconsistency."
this is true, I didn't notice that the two paragraphs were removed

2022-07-25 20:44 UTC, merged

2022-07-25 20:46 UTC, otmon76 commented
I am sorry I mistakenly merged it but the suggestions were applied.

2022-07-25 21:32 UTC, otmon76 commented
/done